### PR TITLE
Bump version to v0.20.2

### PR DESCRIPTION
**Pull request by tdido**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
```
bleak 0.20.2 requires dbus-fast, which is not installed.
```
Unfortunately, `dbus-fast` is not yet available on `conda-forge`.

**Comment by jan-janssen** [comment]
For future reference https://github.com/conda-forge/staged-recipes/pull/23349

**Comment by tdido** [comment]
@conda-forge-admin, please restart ci

**Comment by tdido** [comment]
@conda-forge-admin please rerender

**Pull request merged**
